config/routes.rb
Rails.application.routes.draw do
  resources :radars

end

app/models/radar.rb
class Radar < ActiveRecord::Base
  scope :recent, ->{ where('updated_at > ?', 1.day.ago) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/radars_controller.rb
class RadarsController < ApplicationController
  before_action :set_radar, only: [:show, :edit, :update, :destroy]

  # GET /radars
  # GET /radars.json
  def index
    
    respond_to do |format|
       format.html { @radars = Radar.all }
       format.json { @radars = Radar.recent }
    end
  end

  # GET /radars/1
  # GET /radars/1.json
  def show
  end

  # GET /radars/new
  def new
    @radar = Radar.new
  end

  # GET /radars/1/edit
  def edit
  end

  # POST /radars
  # POST /radars.json
  def create
    @radar = Radar.new(radar_params)

    respond_to do |format|
      if @radar.save
        format.html { redirect_to @radar, notice: 'Radar was successfully created.' }
        format.json { render :show, status: :created, location: @radar }
      else
        format.html { render :new }
        format.json { render json: @radar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /radars/1
  # PATCH/PUT /radars/1.json
  def update
    respond_to do |format|
      if @radar.update(radar_params)
        format.html { redirect_to @radar, notice: 'Radar was successfully updated.' }
        format.json { render :show, status: :ok, location: @radar }
      else
        format.html { render :edit }
        format.json { render json: @radar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /radars/1
  # DELETE /radars/1.json
  def destroy
    @radar.destroy
    respond_to do |format|
      format.html { redirect_to radars_url, notice: 'Radar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_radar
      @radar = Radar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def radar_params
      params.require(:radar).permit(:latitude, :longitude, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/radars_helper.rb
module RadarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RadarsPt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/radars/_form.html.erb
<%= form_for(@radar) do |f| %>
  <% if @radar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@radar.errors.count, "error") %> prohibited this radar from being saved:</h2>

      <ul>
      <% @radar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/radars/edit.html.erb
<h1>Editing Radar</h1>

<%= render 'form' %>

<%= link_to 'Show', @radar %> |
<%= link_to 'Back', radars_path %>

app/views/radars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Radars</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @radars.each do |radar| %>
      <tr>
        <td><%= radar.latitude %></td>
        <td><%= radar.longitude %></td>
        <td><%= radar.description %></td>
        <td><%= link_to 'Show', radar %></td>
        <td><%= link_to 'Edit', edit_radar_path(radar) %></td>
        <td><%= link_to 'Destroy', radar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Radar', new_radar_path %>

app/views/radars/new.html.erb
<h1>New Radar</h1>

<%= render 'form' %>

<%= link_to 'Back', radars_path %>

app/views/radars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @radar.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @radar.longitude %>
</p>

<p>
  <strong>Description:</strong>
  <%= @radar.description %>
</p>

<%= link_to 'Edit', edit_radar_path(@radar) %> |
<%= link_to 'Back', radars_path %>